version: '3.1'
services:
  stat-service:
    build: stat-service
    image: stat-service
    container_name: stat-service
    ports:
      - "9090:9090"
    depends_on:
      - stat-db
    environment:
      - spring.datasource.url=jdbc:postgresql://stat-db:5432/stat
      - spring.datasource.username=root
      - spring.datasource.password=root

  stat-db:
    image: postgres:14-alpine
    container_name: stat-db
    volumes:
      - /var/lib/postgresql/data/
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=stat
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  ewm-service:
    build: ewm-service
    image: ewm-service
    container_name: ewm-service
    ports:
      - "8080:8080"